name: Continuous Integration
on: 
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build tests on Docker
        run: docker build --target test --tag todo-app:test .
      - name: Run tests
        run: docker run todo-app:test