name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
env:
  AZURE_WEBHOOK_URL: "${{ secrets.AZURE_WEBHOOK_URL }}"
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build tests on Docker
        run: docker build --target test --tag todo-app:test .

      - name: Run tests
        run: docker run todo-app:test

  deploy:
    name: Publish
    needs: build
    if: (github.event_name == 'push' && github.ref == 'refs/heads/module-12')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          target: production
          tags: framasw/todo-app:latest,framasw/todo-app:${{ github.sha }}

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Call Azure webhook
        run: curl -dH -X POST "$(terraform output -raw webhook_url)"
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_prefix: prod
      TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
      TF_VAR_github_oauth_client_id: ${{ secrets.GITHUB_OAUTH_CLIENT_ID }}
      TF_VAR_github_oauth_client_secret: ${{ secrets.GITHUBOAUTH_CLIENT_SECRET }}