name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build tests on Docker
        run: docker build --target test --tag todo-app:test .

      - name: Run tests
        run: docker run todo-app:test

  deploy:
    name: Publish
    needs: build
    if: (github.event_name == 'push' && github.ref == 'refs/heads/module-8') # TODO: Change branch to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          target: production
          tags: framasw/todo-app:latest,framasw/todo-app:${{ github.sha }}

      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Tag Docker image for Heroku
        run: docker tag framasw/todo-app:latest registry.heroku.com/framasw-todo-app/web

      - name: Push to Heroku
        run: docker push registry.heroku.com/framasw-todo-app/web

      - name: Release on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a framasw-todo-app web