name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build tests on Docker
        run: docker build --target test --tag todo-app:test .

      - name: Run tests
        run: docker run todo-app:test

  deploy:
    name: Publish
    needs: build
    if: (github.event_name == 'push' && github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          target: production
          tags: framasw/todo-app:latest,framasw/todo-app:${{ github.sha }}

      - name: Call Azure webhook
        run: curl -dH -X POST ${{ secrets.AZURE_WEBHOOK_URL }}
